### ISSUE TITLE
Monitor checksum failures in pg12+

### ISSUE THREAD

**Issue by keithf4** [CrunchyData/pgmonitor#125]
New columns in `pg_stat_database` track checksum failure count (`checksum_failures` & `checksum_last_failure`.

https://www.postgresql.org/docs/12/monitoring-stats.html#PG-STAT-DATABASE-VIEW

Need to check if/how this can be reset.

**Comment by keithf4** [comment]
Proposed query/metrics for monitoring checksum failure. Only thing I can't figure out right now is what to do after the checksum errors have been fixed. Currently can't see any way to reset either the count or the time.
```
ccp_checksum_failure:
  query: "SELECT datname AS dbname
            , checksum_failures AS count
            , coalesce(extract(epoch from (now() - checksum_last_failure)), 0) AS time_since_last_failure_seconds 
          FROM pg_stat_database;"
  metrics:
    - dbname:
        usage: "LABEL"
        description: "Database name"
    - count:
        usage: "GAUGE"
        description: "Total number of checksum failures on this database"
    - time_since_last_failure_seconds:
        usage: "GAUGE"
        description: "Time interval in seconds since the last checksum failure was encountered"

```
