### ISSUE TITLE
Failover example alert

### ISSUE THREAD

**Issue by keithf4** [CrunchyData/pgmonitor#180]
See about adding the following failover alert into the default rules file. Should be able to add it as an active alert and not commented out since it's not specific to any one system like the current failover example rule

```
# Monitor for a failover event by watching for the recovery status value to change within specified time period
- alert: PGRecoveryStatusSwitch
  expr: ccp_is_in_recovery_status != ccp_is_in_recovery_status offset 5m 
  for: 60s
  labels:
    service: postgresql
    severity: critical
    severity_num: 300
  annotations:
    summary: '{{ $labels.job }} has had a PostgreSQL failover event. Please check systems involved in this cluster for more details'
```
