### ISSUE TITLE
Custom url path for accessing grafana service via ingress

### ISSUE THREAD

**Issue by aprilito1965** [CrunchyData/pgmonitor#240]
Hi!

Is there a way to pass a parameter during kubernetes deploy to change default url path used for accessing grafana service (via ingress resource for example)?
It is actually posible with something like that:

**[server]
domain = example.com
root_url = http://example.com/monitoring/**

In my other grafana instance (included in prometheus-stack helm chart) i use this values.yaml snippet:

**grafana.ini:
    server:
      domain: examplehost.com
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/graf/"
      serve_from_sub_path: true**
      
I know that it is also a way to do it with env:

grafana:
  env:
    GF_SERVER_ROOT_URL: https://myhostname.example.com/grafana
    GF_SERVER_SERVE_FROM_SUB_PATH: 'true'

Thank you!

**Comment by keithf4** [comment]
Apologies for the delay on response. I'm not familiar with any way to do this myself. Asking some of my work colleagues that do more container work if they may have any ideas.

**Comment by andrewlecuyer** [comment]
@aprilito1965 I recommend you check out the `kustomize` installer we now have for deploying PgMonitor as part of the PGO v5 monitoring stack: 

https://github.com/CrunchyData/postgres-operator-examples/tree/main/kustomize/monitoring

With the `kustomize` installer you should be able to easily add an overlay to include the desired enviroment variables (`GF_SERVER_ROOT_URL` and `GF_SERVER_SERVE_FROM_SUB_PATH`) in your Grafana deployment.

For instance, you can create a file containing the custom env vars that you would like to apply, e.g.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crunchy-grafana
spec:
  template:
    spec:
      containers:
      - name: grafana
        env:
        - name: GF_SERVER_ROOT_URL
          value: https://myhostname.example.com/grafana
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
```

And then add it as a patch in a `kustomization.yaml` file:

```yaml
patchesStrategicMerge:
- custom-env.yaml
```

And the end result should then be the desired environment variables in the Grafana Pod:

```yaml
$ kubectl describe pod crunchy-grafana-79cb6746df-s4t7b | grep Environment -A 2
    Environment:
      GF_SERVER_ROOT_URL:                https://myhostname.example.com/grafana
      GF_SERVER_SERVE_FROM_SUB_PATH:     true
```
