### ISSUE TITLE
prefix all grafana endpoints and APIs by a custom base path

### ISSUE THREAD

**Issue by rahulbreezo** [CrunchyData/pgmonitor#272]
**Describe the issue:**
I have nginx ingress controller that is in front of grafan service.

and aws alb ingress controller in front of nginx ingress.

I want to use rewrite to direct `alb-url/monitor` to grafana monitor.

How can configure grafan so that grafana endpoints and all APIs are prefixed by `monitor`. ?

**Describe the expected behavior:**

prefix all grafana endpoints and APIs by a custom base path

**Tell us about your environment:**  
- pgMonitor version:  5.0.4
- Container or non-container: container  
- Container name / image:  registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.4-0
- Grafana version:  grafana/grafana:7.4.5

**Comment by andrewlecuyer** [comment]
@rahulbreezo I recommend you checkout the `root_url` and `serve_from_sub_path` settings [provided by Grafana](https://grafana.com/docs/grafana/latest/administration/configuration/#root_url), which should give you the behavior you are looking for.

These can be set in the [Grafana Deployment spec](https://github.com/CrunchyData/postgres-operator-examples/blob/main/kustomize/monitoring/deploy-grafana.yaml) as follows:

```yaml
spec:
      containers:
      - env:
        - name: GF_SERVER_ROOT_URL
          value: http://some.root.url/monitor
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
```
