### ISSUE TITLE
ccp_nodemx_data_disk fails when calling function due to mismatched types

### ISSUE THREAD

**Issue by sharkymcdongles** [CrunchyData/pgmonitor#304]
**Describe the issue:**
The exporter continually throws this error:

`queryNamespaceMappings returned 1 errors`

When I investigate further I found that it is due to this metric:
ccp_nodemx_data_disk:
```
  query: "SELECT mount_point,fs_type,total_bytes,available_bytes,total_file_nodes,free_file_nodes
          FROM monitor.proc_mountinfo() m
          JOIN monitor.fsinfo(m.mount_point) f USING (major_number, minor_number)
          WHERE m.mount_point IN ('/pgdata', '/pgwal') OR
                m.mount_point like '/tablespaces/%'"
  metrics:
    - mount_point:
        usage: "LABEL"
        description: "mount point"
    - fs_type:
        usage: "LABEL"
        description: "File system type"
    - total_bytes:
        usage: "GAUGE"
        description: "Size in bytes"
    - available_bytes:
        usage: "GAUGE"
        description: "Available size in bytes"
    - total_file_nodes:
        usage: "GAUGE"
        description: "Total file nodes"
    - free_file_nodes:
        usage: "GAUGE"
        description: "Available file nodes"
```

**When I run this query manually I get this:**
```
postgres=# SELECT mount_point,fs_type,total_bytes,available_bytes,total_file_nodes,free_file_nodes
postgres-#           FROM monitor.proc_mountinfo() m
postgres-#           JOIN monitor.fsinfo(m.mount_point) f USING (major_number, minor_number)
postgres-#           WHERE m.mount_point IN ('/pgdata', '/pgwal') OR
postgres-#                 m.mount_point like '/tablespaces/%';
ERROR:  query-specified return tuple and function return type are not compatible
DETAIL:  Expected numeric, got bigint
```

This postgres is created via the crunchy postgres operator.

**Describe the expected behavior:**

**Tell us about your environment:**  
- pgMonitor version:  N/A
- Container or non-container:  container
- Container name / image:  registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.4-0
- Operating System for non-container:  N/A
- PostgreSQL Version:  13.5
- Exporter(s) in use (incl. version):  registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.4-0
- Prometheus version:  N/A
- AlertManager version:  N/A
- Grafana version:  N/A
