### ISSUE TITLE
blackbox_exporter causing tls errors in syslog

### ISSUE THREAD

**Issue by keithf4** [CrunchyData/pgmonitor#333]
**Describe the issue:**

Seeing the following errors in syslog 
```
May 11 17:56:17 vagrant prometheus[5864]: ts=2023-05-11T17:56:17.871Z caller=stdlib.go:105 level=error component=web caller="http: TLS handshake error from 127.0.0.1:36874" msg=EOF
May 11 17:56:26 vagrant alertmanager[5920]: 2023/05/11 17:56:26 http: TLS handshake error from 127.0.0.1:43372: EOF
May 11 17:56:45 vagrant grafana[6501]: server.go:3197: http: TLS handshake error from 127.0.0.1:56404: EOF
```
Discovered this was coming from the blackbox_exporter when these services were configured for TLS.

Found the option for the tcp probe to initiate with tls and that gets rid of this error. However, then other services not running on tls fail their tcp probe.

Will need to configure a separate probe in blackbox exporter for testing tls connections. Then configure a different scraper to look in a blackbox exporter tls folder for those targets

Possible solutions to try...

`/etc/blackbox_exporter/crunchy-blackbox.yml`
```
modules:
  tcp_connect:
    prober: tcp
    tcp:
      preferred_ip_protocol: ip4
  tcp_connect_tls:
    prober: tcp
    tcp:
      preferred_ip_protocol: ip4
      tls: true
```

`/etc/prometheus/crunchy-prometheus` (below non-tls blackbox scrape)
```
  - job_name: 'blackbox_tcp_tls_services'
    metrics_path: /probe
    params:
      module: [tcp_connect_tls]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
    scrape_interval: 30s
    file_sd_configs:
    - files:
      - /etc/prometheus/auto.blackbox.tls.d/*.yml
```

**Tell us about your environment:**  
- pgMonitor version:  4.8
- Container or non-container:  N/A
- Container name / image:  N/A
- Operating System for non-container:  RHEL
- PostgreSQL Version:  N/A
- Exporter(s) in use (incl. version):  blackbox
- Prometheus version:  all
- AlertManager version:  all
- Grafana version:  all
