### ISSUE TITLE
ccp_is_in_recovery_status: Metric description mistake

### ISSUE THREAD

**Issue by Mmefko** [CrunchyData/pgmonitor#375]
*ccp_is_in_recovery_status*. It looks like the description in the documentation contains a mistake.

**Current description:** [ccp_is_in_recovery_status](https://github.com/CrunchyData/pgmonitor/blob/0d201b6f1da832a5f4f26581a023ddf2874394fc/hugo/content/exporter/_index.md?plain=1#L343C4-L343C4) - Current value of the pg_is_in_recovery() function expressed as 2 for true (instance is a replica) and 1 for false (instance is a primary)

* 2 - replica
* 1 - primary

And on the other side - query: 

```yaml
ccp_is_in_recovery:
        query: "SELECT CASE WHEN pg_is_in_recovery = true THEN 1 ELSE 2 END AS status from pg_is_in_recovery();"
        metrics:
          - status:
```
* 1 - replica
* 2 - primary

**Expected behavior:** Correct description of the metric
* *ccp_is_in_recovery_status* - Current value of the pg_is_in_recovery() function expressed as 1 for true (instance is a replica) and 2 for false (instance is a primary)
