### ISSUE TITLE
postgres_exporter: command not found

### ISSUE THREAD

**Issue by BenetatosG** [CrunchyData/pgmonitor#386]
**Describe the issue:**
Exporter fails to start

**Describe the expected behavior:**
I am using the kustomize approach for postgres operator, after I added exporter config, the pod starts but the exporter container fails make the PG_EXP_HOME env variable for postgres_exporter.

I managed to go into the container and start the exporter myself.

```
kubectl logs -n ergo ergo-postgres-instance1-d4mv-0 -c exporter
Starting postgres_exporter with the following flags...
--extend.query-path=/tmp/queries.yml --web.listen-address=:9187
environment: line 10: postgres_exporter: command not found
```

kustomize.yaml
```
 monitoring:
    pgmonitor:
      exporter:
       image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.0-0
```

I have looked into the start.sh and can't really tell why the export is not working

**Tell us about your environment:**  
- Container name / image:  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.0-0
